//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendingMachine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages_FR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages_FR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VendingMachine.Properties.Messages_FR", typeof(Messages_FR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;SOLDE&apos; - Afficher le montant du solde dans la machine.
        /// </summary>
        internal static string Command1Text {
            get {
                return ResourceManager.GetString("Command1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;AFFICHER&apos; - Afficher les produits dans la machine.
        /// </summary>
        internal static string Command2Text {
            get {
                return ResourceManager.GetString("Command2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;RECHARGE&apos; - Machine de recharge.
        /// </summary>
        internal static string Command3Text {
            get {
                return ResourceManager.GetString("Command3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;SÉLECTIONNER&apos; - Sélectionner un produit.
        /// </summary>
        internal static string Command4Text {
            get {
                return ResourceManager.GetString("Command4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;HISTOIRE&apos; - Imprimer les 10 derniers enregistrements de vente.
        /// </summary>
        internal static string Command5Text {
            get {
                return ResourceManager.GetString("Command5Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;LANGUE&apos; - Changer de langue.
        /// </summary>
        internal static string Command6Text {
            get {
                return ResourceManager.GetString("Command6Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;SORTIR&apos; - Annulez la transaction et déconnectez-vous du système..
        /// </summary>
        internal static string Command7Text {
            get {
                return ResourceManager.GetString("Command7Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quelle commande préférez-vous ? Veuillez taper la commande appropriée comme indiqué ci-dessous:.
        /// </summary>
        internal static string CommandHeaderTitle {
            get {
                return ResourceManager.GetString("CommandHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez la langue que vous souhaitez modifier. &lt;EN|DE|FR&gt;.
        /// </summary>
        internal static string EnterLanguageText {
            get {
                return ResourceManager.GetString("EnterLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialisation du distributeur automatique....
        /// </summary>
        internal static string InitalizeMachineText {
            get {
                return ResourceManager.GetString("InitalizeMachineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERREUR] Commande non valide..
        /// </summary>
        internal static string InvalidCommand {
            get {
                return ResourceManager.GetString("InvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERREUR] Entrée invalide..
        /// </summary>
        internal static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langage machine remplacé par:.
        /// </summary>
        internal static string LanguageChangedText {
            get {
                return ResourceManager.GetString("LanguageChangedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        internal static string LanguageName {
            get {
                return ResourceManager.GetString("LanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le distributeur automatique est prêt à l&apos;emploi..
        /// </summary>
        internal static string MachineReadyText {
            get {
                return ResourceManager.GetString("MachineReadyText", resourceCulture);
            }
        }
    }
}
