//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendingMachine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages_DE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VendingMachine.Properties.Messages_DE", typeof(Messages_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;GLEICHGEWICHT&apos; - Zeigt den Saldobetrag im Gerät an.
        /// </summary>
        internal static string Command1Text {
            get {
                return ResourceManager.GetString("Command1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;SHOW&apos; - Produkte in der Maschine anzeigen.
        /// </summary>
        internal static string Command2Text {
            get {
                return ResourceManager.GetString("Command2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;NACHFÜLLUNG&apos; - Nachfüllmaschine.
        /// </summary>
        internal static string Command3Text {
            get {
                return ResourceManager.GetString("Command3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;AUSWÄHLEN&apos; - Ausgewähltes Produkt.
        /// </summary>
        internal static string Command4Text {
            get {
                return ResourceManager.GetString("Command4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;GESCHICHTE&apos; - Drucken Sie die letzten 10 Verkaufsdatensätze.
        /// </summary>
        internal static string Command5Text {
            get {
                return ResourceManager.GetString("Command5Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;SPRACHE&apos; - Sprache ändern.
        /// </summary>
        internal static string Command6Text {
            get {
                return ResourceManager.GetString("Command6Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;AUSFAHRT&apos; - Brechen Sie die Transaktion ab und trennen Sie die Verbindung zum System.
        /// </summary>
        internal static string Command7Text {
            get {
                return ResourceManager.GetString("Command7Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welchen Befehl würden Sie bevorzugen? Bitte geben Sie den richtigen Befehl wie unten gezeigt ein:.
        /// </summary>
        internal static string CommandHeaderTitle {
            get {
                return ResourceManager.GetString("CommandHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie die Sprache ein, die Sie ändern möchten. &lt;EN|DE|FR&gt;.
        /// </summary>
        internal static string EnterLanguageText {
            get {
                return ResourceManager.GetString("EnterLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verkaufsautomat wird initialisiert....
        /// </summary>
        internal static string InitalizeMachineText {
            get {
                return ResourceManager.GetString("InitalizeMachineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERROR] Ungültiger Befehl..
        /// </summary>
        internal static string InvalidCommand {
            get {
                return ResourceManager.GetString("InvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [FEHLER] Ungültige Eingabe..
        /// </summary>
        internal static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maschinensprache geändert in:.
        /// </summary>
        internal static string LanguageChangedText {
            get {
                return ResourceManager.GetString("LanguageChangedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        internal static string LanguageName {
            get {
                return ResourceManager.GetString("LanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verkaufsautomat ist einsatzbereit..
        /// </summary>
        internal static string MachineReadyText {
            get {
                return ResourceManager.GetString("MachineReadyText", resourceCulture);
            }
        }
    }
}
