//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendingMachine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VendingMachine.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;BALANCE&apos; - Display Balance Amount in Machine.
        /// </summary>
        internal static string Command1Text {
            get {
                return ResourceManager.GetString("Command1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;SHOW&apos; - Show Products in Machine.
        /// </summary>
        internal static string Command2Text {
            get {
                return ResourceManager.GetString("Command2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;REFILL&apos; - Refill Machine.
        /// </summary>
        internal static string Command3Text {
            get {
                return ResourceManager.GetString("Command3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;SELECT&apos; - Select Product.
        /// </summary>
        internal static string Command4Text {
            get {
                return ResourceManager.GetString("Command4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;HISTORY&apos; - Print Last 10 Sale Records.
        /// </summary>
        internal static string Command5Text {
            get {
                return ResourceManager.GetString("Command5Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;LANGUAGE&apos; - Change Language.
        /// </summary>
        internal static string Command6Text {
            get {
                return ResourceManager.GetString("Command6Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;EXIT&apos; - Cancel the transaction and disconnect from the system.
        /// </summary>
        internal static string Command7Text {
            get {
                return ResourceManager.GetString("Command7Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which command would you prefer? Please type the proper command as shown below:.
        /// </summary>
        internal static string CommandHeaderTitle {
            get {
                return ResourceManager.GetString("CommandHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Language you want to change. &lt;EN|DE|FR&gt;.
        /// </summary>
        internal static string EnterLanguageText {
            get {
                return ResourceManager.GetString("EnterLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Vending Machine....
        /// </summary>
        internal static string InitalizeMachineText {
            get {
                return ResourceManager.GetString("InitalizeMachineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERROR] Invalid command..
        /// </summary>
        internal static string InvalidCommand {
            get {
                return ResourceManager.GetString("InvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERROR] Invalid input..
        /// </summary>
        internal static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Language changed to:.
        /// </summary>
        internal static string LanguageChangedText {
            get {
                return ResourceManager.GetString("LanguageChangedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LanguageName {
            get {
                return ResourceManager.GetString("LanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vending Machine is ready to use..
        /// </summary>
        internal static string MachineReadyText {
            get {
                return ResourceManager.GetString("MachineReadyText", resourceCulture);
            }
        }
    }
}
